<a href="https://colab.research.google.com/github/BenJoshMudi/GOMYCODE.BEN/blob/main/Grades_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
grades = np.array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])
grades

array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])

In [ ]:
# to calculate the mean of the grades
grades_mean = np.mean(grades)
grades_mean

87.5

In [ ]:
# to calculate the median of the grades
grades_median = np.median(grades)
grades_median


88.5

In [ ]:
# to calculate the standard deviation of the grades
grades_std = np.std(grades)
grades_std

6.591661399070799

In [ ]:
# to get the maximum grades
grades_max = np.max(grades)
print("The maximum grade is:", grades_max)

The maximum grade is: 98


In [ ]:
# to get the minimum grades
grades_min = np.min(grades)
grades_min
print("The minimum grade is:", grades_min)

The minimum grade is: 75


In [ ]:
arcending_indices = np.argsort(grades)
arcending_grades = grades[arcending_indices]
arcending_grades

array([75, 80, 83, 85, 88, 89, 90, 92, 95, 98])

In [ ]:
# to get the index
index_highest_grades = np.max(arcending_indices)
index_highest_grades

9

In [ ]:
# to count the grades above 90 use grades[grades > 90]
grades_above_90 = len(grades[grades>90])
grades_above_90

3

In [ ]:
# to calculate percentage of student who scored above 90.
grades_percent_above_90 = np.mean(grades[grades>90]) / 100
grades_percent_above_90
print("Number of students who scored above 90:", grades_percent_above_90)

Number of students who scored above 90: 0.95


In [ ]:
# to calculate the percentage of student who scored below 70
grades_percent_below_75 = np.mean(grades[grades<75]) / 100
grades_percent_below_75
print("percentage of students who scored below 75:", grades_percent_below_75)

percentage of students who scored below 75: nan


/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.10/dist-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)


In [ ]:
# to extract all the grades above 75
high_performers = grades[grades>90]
high_performers
print("students who scored above 75:", high_performers)

students who scored above 75: [92 95 98]


In [ ]:
passing_grades = grades[grades>75]
passing_grades

array([85, 90, 88, 92, 95, 80, 98, 89, 83])